spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: chenchen@2016150056
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:config.xml